#:schema node_modules/wrangler/config-schema.json
name = "zaraz-consent-style-gallery"
main = "dist/index.js"
compatibility_date = "2024-11-12"
compatibility_flags = ["nodejs_compat"]
assets = { directory = "./public", binding = "ASSETS", html_handling = "force-trailing-slash", not_found_handling = "404-page" }
routes = [
  { pattern = "consent-designs.zaraz.com", custom_domain = true }
]

# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true

[[d1_databases]]
binding = "DB"
database_name = "zaraz-consent-style-gallery"
database_id = "975b3810-7fcf-4b9a-ab3e-3b30ac023793"
